export const CacheKey = {
  MediaSourcesSettings: 'media-sources-settings',
  Directory: 'directory',
  GalleryAll: 'gallery-all',
  GalleryPhotos: 'gallery-photos',
  GalleryVideos: 'gallery-videos',
  AlbumsAll: 'albums-all',
  AlbumSingle: 'albums-single',
  Logs: 'logs',
  AssetSingle: 'asset-single',
  IsFirstUser: 'is-first-user',
  AllowsUserSelfRegistration: 'allows-user-self-registration',
  UiSettings: 'ui-settings',
  SystemSettings: 'system-settings',
  StorageStats: 'storage-stats',
  CamerasAll: 'cameras-all',
  CameraSingle: 'camera-single',
};
